server:
  servlet:
    context-path: /financa
  port: 5000
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  data:
    jpa:
      properties:
        show-sql: 'true'
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: financa
  jackson:
    serialization:
      write_dates_as_timestamps: false
  liquibase:
    change-log: db\changelog\changelog-master.yml