spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FINANCA?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  liquibase:
    enabled: true